Items = {
    { name = "Achievements in Daytime Programming - Programs\t1966-1966", pos = {}, },
    { name = "Achievements in Educational Television - Individuals\t1966-1966", pos = {}, },
    { name = "Actress of the Year - Series\t1974-1974", pos = {}, },
    { name = "Best Art Direction or Scenic Design - For a Musical or Variety Single Program of a Series or a Special Program\t1974-1974", pos = {}, },
    { name = "Best Cinematography for Entertainment Programming - For a Series or a Single Program of a Series\t1974-1974", pos = {}, },
    { name = "Best Directing in Comedy\t1974-1974", pos = {}, },
    { name = "Best Directing in Drama - A Single Program of a Series with Continuing Characters and/or Theme\t1974-1974", pos = {}, },
    { name = "Best Directing in Variety or Music\t1974-1974", pos = {}, },
    { name = "Best Film Editing for Entertainment Programming - For a Series or a Single Program of a Series\t1974-1974", pos = {}, },
    { name = "Best Lead Actor in a Comedy Series\t1974-1974", pos = {}, },
    { name = "Best Lead Actor in a Drama Series\t1974-1974", pos = {}, },
    { name = "Best Lead Actor in a Limited Series\t1974-1974", pos = {}, },
    { name = "Best Lead Actress in a Comedy Series\t1974-1974", pos = {}, },
    { name = "Best Lead Actress in a Drama Series\t1974-1974", pos = {}, },
    { name = "Best Lead Actress in a Limited Series\t1974-1974", pos = {}, },
    { name = "Best Music Composition - For a Series, a Single Program of a Series\t1974-1974", pos = {}, },
    { name = "Best Music Direction of a Variety, Music or Dramatic Program\t1974-1974", pos = {}, },
    { name = "Best Song or Theme\t1974-1974", pos = {}, },
    { name = "Best Supporting Actor in Comedy\t1974-1974", pos = {}, },
    { name = "Best Supporting Actor in Comedy-Variety, Variety or Music\t1974-1974", pos = {}, },
    { name = "Best Supporting Actor in Drama\t1974-1974", pos = {}, },
    { name = "Best Supporting Actress in Comedy\t1974-1974", pos = {}, },
    { name = "Best Supporting Actress in Comedy-Variety, Variety or Music\t1974-1974", pos = {}, },
    { name = "Best Supporting Actress in Drama\t1974-1974", pos = {}, },
    { name = "Best Writing in Comedy\t1974-1974", pos = {}, },
    { name = "Best Writing in Drama\t1974-1974", pos = {}, },
    { name = "Best Writing in Variety or Music\t1974-1974", pos = {}, },
    { name = "Creative Achievement in Interactive Media\t2011-2011", pos = {}, },
    { name = "Exceptional Merit in Documentary Filmmaking\t2012-2020", pos = {}, },
    { name = "Exceptional Merit in Nonfiction Filmmaking\t2005-2010", pos = {}, },
    { name = "Individual Achievements in Art Direction and Allied Crafts - Art Direction\t1966-1966", pos = {}, },
    { name = "Individual Achievements in Art Direction and Allied Crafts - Costume Design\t1966-1966", pos = {}, },
    { name = "Individual Achievements in Art Direction and Allied Crafts - Mechanical Special Effects\t1966-1967", pos = {}, },
    { name = "Individual Achievements in Art Direction and Allied Crafts - Set Direction\t1966-1966", pos = {}, },
    { name = "Individual Achievements in Cinematography - Cinematography\t1966-1967", pos = {}, },
    { name = "Individual Achievements in Cinematography - Photographic Special Effects\t1967-1967", pos = {}, },
    { name = "Individual Achievements in Cinematography - Special\t1966-1966", pos = {}, },
    { name = "Individual Achievements in Electronic Production - Audio Engineering\t1966-1966", pos = {}, },
    { name = "Individual Achievements in Electronic Production - Technical Directors\t1966-1967", pos = {}, },
    { name = "Individual Achievements in Electronic Production - Video Tape Editing\t1967-1967", pos = {}, },
    { name = "Individual Achievements in Film Editing\t1966-1966", pos = {}, },
    { name = "Individual Achievements in Film and Sound Editing\t1967-1967", pos = {}, },
    { name = "Individual Achievements in Music - Arranging\t1966-1966", pos = {}, },
    { name = "Individual Achievements in Music - Composition\t1966-1967", pos = {}, },
    { name = "Individual Achievements in Music - Conducting\t1966-1966", pos = {}, },
    { name = "Individual Achievements in Sound Editing\t1966-1966", pos = {}, },
    { name = "Oustanding Art Direction for a Variety or Music Program\t2003-2003", pos = {}, },
    { name = "Outstanding Achievement by Individuals in Daytime Drama\t1973-1973", pos = {}, },
    { name = "Outstanding Achievement by Individuals in Daytime Programming\t1973-1973", pos = {}, },
    { name = "Outstanding Achievement by a Performer in Music or Variety\t1972-1972", pos = {}, },
    { name = "Outstanding Achievement by a Supporting Performer in Music or Variety\t1973-1973", pos = {}, },
    { name = "Outstanding Achievement in Any Area of Creative Technical Crafts\t1970-1975", pos = {}, },
    { name = "Outstanding Achievement in Art Direction and Scenic Design\t1960-1969", pos = {}, },
    { name = "Outstanding Achievement in Art Direction or Scenic Design - Dramatic Special or Feature Length Film Made for TV\t1976-1976", pos = {}, },
    { name = "Outstanding Achievement in Art Direction or Scenic Design - For a Dramatic Program or Feature Length Film Made for Television, a Single Program of a Series or a Special Program\t1972-1973", pos = {}, },
    { name = "Outstanding Achievement in Art Direction or Scenic Design - For a Dramatic Program or Feature Length Film, a Single Program of a Series or a Special Program\t1971-1971", pos = {}, },
    { name = "Outstanding Achievement in Art Direction or Scenic Design - For a Musical or Variety Single Program of a Series or a Special Program\t1971-1973", pos = {}, },
    { name = "Outstanding Achievement in Art Direction or Scenic Design - Single Episode of a Comedy, Drama or Limited Series\t1976-1976", pos = {}, },
    { name = "Outstanding Achievement in Art Direction or Scenic Design - Single Episode of a Comedy-Variety or Music Series or a Comedy-Variety or Music Special\t1976-1976", pos = {}, },
    { name = "Outstanding Achievement in Art Direction or Scenic Design: For a Dramatic Program\t1970-1970", pos = {}, },
    { name = "Outstanding Achievement in Broadcast Journalism\t1977-1977", pos = {}, },
    { name = "Outstanding Achievement in Casting for a Miniseries or a Special\t1989-1991", pos = {}, },
    { name = "Outstanding Achievement in Children's Programming - Entertainment/Fictional\t1973-1973", pos = {}, },
    { name = "Outstanding Achievement in Children's Programming - Individuals\t1968-1972", pos = {}, },
    { name = "Outstanding Achievement in Children's Programming - Informational/Factual\t1973-1973", pos = {}, },
    { name = "Outstanding Achievement in Children's Programming - Programs\t1968-1972", pos = {}, },
    { name = "Outstanding Achievement in Choreography\t1970-1988", pos = {}, },
    { name = "Outstanding Achievement in Cinematography\t1968-1969", pos = {}, },
    { name = "Outstanding Achievement in Cinematography for Entertainment Programming - For a Series or a Single Program of a Series\t1970-1973", pos = {}, },
    { name = "Outstanding Achievement in Cinematography for Entertainment Programming - For a Special or Feature Length Program Made for Television\t1970-1970", pos = {}, },
    { name = "Outstanding Achievement in Cinematography for Entertainment Programming for a Series\t1975-1976", pos = {}, },
    { name = "Outstanding Achievement in Cinematography for Entertainment Programming for a Special\t1975-1976", pos = {}, },
    { name = "Outstanding Achievement in Cinematography for Television\t1960-1964", pos = {}, },
    { name = "Outstanding Achievement in Composing Original Music\t1963-1963", pos = {}, },
    { name = "Outstanding Achievement in Composing Original Music for Television\t1964-1964", pos = {}, },
    { name = "Outstanding Achievement in Costume Design\t1970-1975", pos = {}, },
    { name = "Outstanding Achievement in Costume Design for Music-Variety\t1976-1977", pos = {}, },
    { name = "Outstanding Achievement in Costume Design for a Drama Special\t1976-1978", pos = {}, },
    { name = "Outstanding Achievement in Costume Design for a Drama or Comedy Series\t1976-1978", pos = {}, },
    { name = "Outstanding Achievement in Costuming\t1985-1985", pos = {}, },
    { name = "Outstanding Achievement in Costuming for a Miniseries or a Special\t1986-1991", pos = {}, },
    { name = "Outstanding Achievement in Costuming for a Series\t1986-1991", pos = {}, },
    { name = "Outstanding Achievement in Daytime Drama - Individuals\t1972-1972", pos = {}, },
    { name = "Outstanding Achievement in Daytime Drama - Programs\t1972-1972", pos = {}, },
    { name = "Outstanding Achievement in Daytime Programming - Individuals\t1968-1972", pos = {}, },
    { name = "Outstanding Achievement in Daytime Programming - Programs\t1968-1972", pos = {}, },
    { name = "Outstanding Achievement in Electronic Camera Work\t1963-1963", pos = {}, },
    { name = "Outstanding Achievement in Electronic Camerawork\t1960-1962", pos = {}, },
    { name = "Outstanding Achievement in Electronic Photography\t1964-1964", pos = {}, },
    { name = "Outstanding Achievement in Film Editing\t1968-1969", pos = {}, },
    { name = "Outstanding Achievement in Film Editing for Entertainment Programming - For a Series or a Single Program of a Series\t1970-1973", pos = {}, },
    { name = "Outstanding Achievement in Film Editing for Entertainment Programming - For a Special or Feature Length Program Made for Television\t1970-1971", pos = {}, },
    { name = "Outstanding Achievement in Film Editing for Entertainment Programming for a Series - For a Single Episode of a Comedy Series\t1976-1976", pos = {}, },
    { name = "Outstanding Achievement in Film Editing for Entertainment Programming for a Series - For a Single Episode of a Drama or Limited Series\t1976-1976", pos = {}, },
    { name = "Outstanding Achievement in Film Editing for Entertainment Programming for a Special\t1976-1976", pos = {}, },
    { name = "Outstanding Achievement in Film Editing for Television\t1960-1963", pos = {}, },
    { name = "Outstanding Achievement in Film Editing for a Series\t1980-1981", pos = {}, },
    { name = "Outstanding Achievement in Film Sound Editing\t1970-1982", pos = {}, },
    { name = "Outstanding Achievement in Film Sound Editing - For a Single Episode of a Regular or Limited Series\t1976-1976", pos = {}, },
    { name = "Outstanding Achievement in Film Sound Editing - For a Special Program\t1976-1976", pos = {}, },
    { name = "Outstanding Achievement in Film Sound Editing for a Series\t1977-1978", pos = {}, },
    { name = "Outstanding Achievement in Film Sound Editing for a Special\t1978-1978", pos = {}, },
    { name = "Outstanding Achievement in Film Sound Mixing\t1970-1982", pos = {}, },
    { name = "Outstanding Achievement in Graphic Design\t1975-2003", pos = {}, },
    { name = "Outstanding Achievement in Graphic Design and Title Sequences\t1976-1989", pos = {}, },
    { name = "Outstanding Achievement in Hairstyling\t1979-1985", pos = {}, },
    { name = "Outstanding Achievement in Hairstyling for a Miniseries or a Special\t1986-1991", pos = {}, },
    { name = "Outstanding Achievement in Hairstyling for a Series\t1986-1991", pos = {}, },
    { name = "Outstanding Achievement in Interactive Television\t2004-2004", pos = {}, },
    { name = "Outstanding Achievement in Lighting Direction\t1970-1973", pos = {}, },
    { name = "Outstanding Achievement in Live or Tape Sound Mixing\t1971-1972", pos = {}, },
    { name = "Outstanding Achievement in Main Title Theme Music\t1988-1991", pos = {}, },
    { name = "Outstanding Achievement in Make-Up\t1976-1976", pos = {}, },
    { name = "Outstanding Achievement in Makeup\t1971-1985", pos = {}, },
    { name = "Outstanding Achievement in Makeup for a Miniseries or a Special\t1986-1991", pos = {}, },
    { name = "Outstanding Achievement in Makeup for a Series\t1986-1991", pos = {}, },
    { name = "Outstanding Achievement in Music Composition - For a Series or a Single Program of a Series\t1972-1972", pos = {}, },
    { name = "Outstanding Achievement in Music Composition - For a Series or a Single Program of a Series (First Year of Music's Use Only)\t1971-1973", pos = {}, },
    { name = "Outstanding Achievement in Music Composition - For a Series or a Single Program of a Series (In Its First Year Only)\t1970-1970", pos = {}, },
    { name = "Outstanding Achievement in Music Composition - For a Special Program\t1971-1971", pos = {}, },
    { name = "Outstanding Achievement in Music Composition for a Limited Series or a Special (Dramatic Underscore)\t1980-1984", pos = {}, },
    { name = "Outstanding Achievement in Music Composition for a Miniseries or a Special (Dramatic Underscore)\t1986-1991", pos = {}, },
    { name = "Outstanding Achievement in Music Composition for a Series\t1975-1976", pos = {}, },
    { name = "Outstanding Achievement in Music Composition for a Series (Dramatic Underscore)\t1977-1991", pos = {}, },
    { name = "Outstanding Achievement in Music Composition for a Special\t1975-1975", pos = {}, },
    { name = "Outstanding Achievement in Music Composition for a Special (Dramatic Underscore)\t1977-1977", pos = {}, },
    { name = "Outstanding Achievement in Music Direction\t1982-1989", pos = {}, },
    { name = "Outstanding Achievement in Music Direction of a Variety, Musical or Dramatic Program\t1970-1973", pos = {}, },
    { name = "Outstanding Achievement in Music and Lyrics\t1982-1991", pos = {}, },
    { name = "Outstanding Achievement in Music, Lyrics and Special Material\t1970-1973", pos = {}, },
    { name = "Outstanding Achievement in Musical Composition\t1968-1969", pos = {}, },
    { name = "Outstanding Achievement in Non-Fiction Programming - Sound Mixing\t2000-2000", pos = {}, },
    { name = "Outstanding Achievement in Original Music Composed for Television\t1962-1962", pos = {}, },
    { name = "Outstanding Achievement in Religious Programming - Individuals\t1973-1973", pos = {}, },
    { name = "Outstanding Achievement in Religious Programming - Programs\t1972-1972", pos = {}, },
    { name = "Outstanding Achievement in Special Musical Material\t1975-1978", pos = {}, },
    { name = "Outstanding Achievement in Special Visual Effects\t1989-1991", pos = {}, },
    { name = "Outstanding Achievement in Sports Programming\t1969-1974", pos = {}, },
    { name = "Outstanding Achievement in Sports Programming - Individuals\t1968-1968", pos = {}, },
    { name = "Outstanding Achievement in Sports Programming - Programs\t1968-1968", pos = {}, },
    { name = "Outstanding Achievement in Tape Sound Mixing\t1976-1978", pos = {}, },
    { name = "Outstanding Achievement in Technical Direction and Electronic Camerawork\t1971-1980", pos = {}, },
    { name = "Outstanding Achievement in Video Tape Editing\t1970-1973", pos = {}, },
    { name = "Outstanding Achievement in Video Tape Editing for a Series\t1976-1978", pos = {}, },
    { name = "Outstanding Achievement in the Field of Children's Programming\t1960-1961", pos = {}, },
    { name = "Outstanding Achievement in the Field of Documentary Programs\t1963-1964", pos = {}, },
    { name = "Outstanding Achievement in the Field of Music for Television\t1961-1961", pos = {}, },
    { name = "Outstanding Achievement within Regularly Scheduled News\t1969-1969", pos = {}, },
    { name = "Outstanding Achievemnet in Art Direction or Scenic Design - For a Single Episode of a Comedy-Variety or Music Series or a Comedy-Variety or Music Special\t1975-1975", pos = {}, },
    { name = "Outstanding Actor in a Short Form Comedy or Drama Series\t2016-2023", pos = {}, },
    { name = "Outstanding Actress in a Short Form Comedy or Drama Series\t2016-2023", pos = {}, },
    { name = "Outstanding Animated Program\t2010-2023", pos = {}, },
    { name = "Outstanding Animated Program (For Programming Less Than One Hour)\t2001-2009", pos = {}, },
    { name = "Outstanding Animated Program (For Programming More Than One Hour)\t1991-2001", pos = {}, },
    { name = "Outstanding Animated Program (For Programming One Hour or Less)\t1991-2000", pos = {}, },
    { name = "Outstanding Animated Program (For Programming One Hour or More)\t2002-2008", pos = {}, },
    { name = "Outstanding Art Direction for Variety, Music or Nonfiction Programming\t2008-2011", pos = {}, },
    { name = "Outstanding Art Direction for Variety, Nonfiction, Reality or Reality-Competition Program\t2014-2014", pos = {}, },
    { name = "Outstanding Art Direction for a Comedy Series\t1978-1978", pos = {}, },
    { name = "Outstanding Art Direction for a Comedy-Variety or Music Series\t1978-1978", pos = {}, },
    { name = "Outstanding Art Direction for a Contemporary Program (Half-Hour or Less)\t2014-2014", pos = {}, },
    { name = "Outstanding Art Direction for a Contemporary or Fantasy Series (Single-Camera)\t2014-2014", pos = {}, },
    { name = "Outstanding Art Direction for a Drama Series\t1978-1978", pos = {}, },
    { name = "Outstanding Art Direction for a Dramatic Special\t1978-1978", pos = {}, },
    { name = "Outstanding Art Direction for a Limited Series or a Special\t1979-1985", pos = {}, },
    { name = "Outstanding Art Direction for a Miniseries or Movie\t2005-2011", pos = {}, },
    { name = "Outstanding Art Direction for a Miniseries or a Movie\t1998-2012", pos = {}, },
    { name = "Outstanding Art Direction for a Miniseries or a Special\t1986-1997", pos = {}, },
    { name = "Outstanding Art Direction for a Miniseries, Movie or a Special\t2000-2004", pos = {}, },
    { name = "Outstanding Art Direction for a Miniseries, or Movie\t2006-2007", pos = {}, },
    { name = "Outstanding Art Direction for a Multi-Camera Series\t2000-2013", pos = {}, },
    { name = "Outstanding Art Direction for a Period Series, Miniseries or a Movie (Single-Camera)\t2014-2014", pos = {}, },
    { name = "Outstanding Art Direction for a Series\t1979-1999", pos = {}, },
    { name = "Outstanding Art Direction for a Single Camera Series\t2000-2010", pos = {}, },
    { name = "Outstanding Art Direction for a Single-Camera Series\t2004-2013", pos = {}, },
    { name = "Outstanding Art Direction for a Variety or Music Program\t1980-2004", pos = {}, },
    { name = "Outstanding Art Direction for a Variety or a Music Program\t1981-1981", pos = {}, },
    { name = "Outstanding Art Direction for a Variety, Music Program or Special\t2005-2005", pos = {}, },
    { name = "Outstanding Art Direction for a Variety, Music Program, or Special\t2006-2006", pos = {}, },
    { name = "Outstanding Art Direction for a Variety, Music or Nonfiction Programming\t2007-2007", pos = {}, },
    { name = "Outstanding Art Direction or Scenic Design for a Comedy Series\t1977-1977", pos = {}, },
    { name = "Outstanding Art Direction or Scenic Design for a Comedy-Variety or Music Series\t1977-1977", pos = {}, },
    { name = "Outstanding Art Direction or Scenic Design for a Drama Series\t1977-1977", pos = {}, },
    { name = "Outstanding Casting for a Comedy Series\t2000-2023", pos = {}, },
    { name = "Outstanding Casting for a Drama Series\t2000-2023", pos = {}, },
    { name = "Outstanding Casting for a Limited Series, Movie or Special\t2016-2020", pos = {}, },
    { name = "Outstanding Casting for a Limited Series, Movie or a Special\t2015-2015", pos = {}, },
    { name = "Outstanding Casting for a Limited or Anthology Series or Movie\t2021-2023", pos = {}, },
    { name = "Outstanding Casting for a Miniseries or a Made for Television Movie\t1999-1999", pos = {}, },
    { name = "Outstanding Casting for a Miniseries or a Movie\t1998-1998", pos = {}, },
    { name = "Outstanding Casting for a Miniseries or a Special\t1996-1996", pos = {}, },
    { name = "Outstanding Casting for a Miniseries, Movie or a Special\t2000-2014", pos = {}, },
    { name = "Outstanding Casting for a Reality Program\t2017-2023", pos = {}, },
    { name = "Outstanding Casting for a Series\t1996-1999", pos = {}, },
    { name = "Outstanding Character Voice-Over Performance\t2014-2023", pos = {}, },
    { name = "Outstanding Children's Program\t1966-2020", pos = {}, },
    { name = "Outstanding Choreography\t1989-2018", pos = {}, },
    { name = "Outstanding Choreography for Scripted Programming\t2019-2023", pos = {}, },
    { name = "Outstanding Choreography for Variety or Reality Programming\t2019-2023", pos = {}, },
    { name = "Outstanding Cinematography for Non-Fiction Programming\t2001-2001", pos = {}, },
    { name = "Outstanding Cinematography for Non-Fiction Programming (Single or Multi-Camera)\t2002-2003", pos = {}, },
    { name = "Outstanding Cinematography for Nonfiction Programming\t2007-2015", pos = {}, },
    { name = "Outstanding Cinematography for Nonfiction Programming (Single or Multi-Camera)\t2004-2005", pos = {}, },
    { name = "Outstanding Cinematography for Nonfiction Programming - Multi-Camera Productions\t2006-2006", pos = {}, },
    { name = "Outstanding Cinematography for Reality Programming\t2007-2015", pos = {}, },
    { name = "Outstanding Cinematography for a Half-Hour Series\t2008-2010", pos = {}, },
    { name = "Outstanding Cinematography for a Limited Series or Movie\t2015-2020", pos = {}, },
    { name = "Outstanding Cinematography for a Limited Series or a Special\t1979-1984", pos = {}, },
    { name = "Outstanding Cinematography for a Limited or Anthology Series or Movie\t2021-2023", pos = {}, },
    { name = "Outstanding Cinematography for a Miniseries or Movie\t2004-2014", pos = {}, },
    { name = "Outstanding Cinematography for a Miniseries or a Movie\t1998-2002", pos = {}, },
    { name = "Outstanding Cinematography for a Miniseries or a Special\t1986-1996", pos = {}, },
    { name = "Outstanding Cinematography for a Multi-Camera Series\t2000-2022", pos = {}, },
    { name = "Outstanding Cinematography for a Nonfiction Program\t2016-2023", pos = {}, },
    { name = "Outstanding Cinematography for a One Hour Series\t2009-2010", pos = {}, },
    { name = "Outstanding Cinematography for a One-Hour Series\t2008-2008", pos = {}, },
    { name = "Outstanding Cinematography for a Reality Program\t2016-2023", pos = {}, },
    { name = "Outstanding Cinematography for a Series\t1979-1999", pos = {}, },
    { name = "Outstanding Cinematography for a Series (Half-Hour)\t2023-2023", pos = {}, },
    { name = "Outstanding Cinematography for a Series (One Hour)\t2023-2023", pos = {}, },
    { name = "Outstanding Cinematography for a Single Camera Series\t2000-2003", pos = {}, },
    { name = "Outstanding Cinematography for a Single-Camera Series\t2004-2016", pos = {}, },
    { name = "Outstanding Cinematography for a Single-Camera Series (Half-Hour)\t2017-2022", pos = {}, },
    { name = "Outstanding Cinematography for a Single-Camera Series (One Hour)\t2017-2022", pos = {}, },
    { name = "Outstanding Cinematography in Entertainment Programming for a Series\t1977-1978", pos = {}, },
    { name = "Outstanding Cinematography in Entertainment Programming for a Special\t1977-1977", pos = {}, },
    { name = "Outstanding Cinematography in Non-Fiction Program\t2000-2000", pos = {}, },
    { name = "Outstanding Classical Music-Dance Program\t1999-2003", pos = {}, },
    { name = "Outstanding Classical Program in the Performing Arts\t1982-1991", pos = {}, },
    { name = "Outstanding Comedy Series\t1966-2023", pos = {}, },
    { name = "Outstanding Comedy-Variety or Music Program\t1979-1979", pos = {}, },
    { name = "Outstanding Comedy-Variety or Music Series\t1975-1978", pos = {}, },
    { name = "Outstanding Competition Program\t2020-2022", pos = {}, },
    { name = "Outstanding Contemporary Costumes\t2018-2022", pos = {}, },
    { name = "Outstanding Contemporary Costumes for a Limited or Anthology Series or Movie\t2023-2023", pos = {}, },
    { name = "Outstanding Contemporary Costumes for a Series\t2023-2023", pos = {}, },
    { name = "Outstanding Contemporary Costumes for a Series, Limited Series, or Movie\t2017-2017", pos = {}, },
    { name = "Outstanding Contemporary Hairstyling\t2020-2023", pos = {}, },
    { name = "Outstanding Contemporary Hairstyling for a Variety, Nonfiction or Reality Program\t2020-2021", pos = {}, },
    { name = "Outstanding Contemporary Makeup (Non-Prosthetic)\t2020-2023", pos = {}, },
    { name = "Outstanding Contemporary Makeup for a Variety, Nonfiction or Reality Program (Non-Prosthetic)\t2020-2021", pos = {}, },
    { name = "Outstanding Continued Performance by an Actor in a Leading Role (Drama Series - Continuing)\t1973-1973", pos = {}, },
    { name = "Outstanding Continued Performance by an Actor in a Leading Role (Drama/Comedy - Limited Episodes)\t1973-1973", pos = {}, },
    { name = "Outstanding Continued Performance by an Actor in a Leading Role in a Comedy Series\t1966-1973", pos = {}, },
    { name = "Outstanding Continued Performance by an Actor in a Leading Role in a Dramatic Series\t1966-1972", pos = {}, },
    { name = "Outstanding Continued Performance by an Actor in a Series (Lead)\t1962-1964", pos = {}, },
    { name = "Outstanding Continued Performance by an Actor in a Supporting Role in a Series\t1969-1969", pos = {}, },
    { name = "Outstanding Continued Performance by an Actress in a Leading Role (Drama Series - Continuing)\t1973-1973", pos = {}, },
    { name = "Outstanding Continued Performance by an Actress in a Leading Role in a Comedy Series\t1966-1973", pos = {}, },
    { name = "Outstanding Continued Performance by an Actress in a Leading Role in a Dramatic Series\t1966-1972", pos = {}, },
    { name = "Outstanding Continued Performance by an Actress in a Series (Lead)\t1962-1964", pos = {}, },
    { name = "Outstanding Continued Performance by an Actress in a Supporting Role in a Series\t1969-1969", pos = {}, },
    { name = "Outstanding Continuing Performance by a Supporting Actor in a Comedy Series\t1975-1978", pos = {}, },
    { name = "Outstanding Continuing Performance by a Supporting Actor in a Drama Series\t1975-1978", pos = {}, },
    { name = "Outstanding Continuing Performance by a Supporting Actress in a Comedy Series\t1975-1978", pos = {}, },
    { name = "Outstanding Continuing Performance by a Supporting Actress in a Drama Series\t1975-1978", pos = {}, },
    { name = "Outstanding Continuing or Single Performance by a Supporting Actor in Variety or Music\t1975-1978", pos = {}, },
    { name = "Outstanding Continuing or Single Performance by a Supporting Actress in Variety or Music\t1975-1978", pos = {}, },
    { name = "Outstanding Costume Design for a Limited Series or a Special\t1979-1985", pos = {}, },
    { name = "Outstanding Costume Design for a Miniseries or a Movie\t1998-1999", pos = {}, },
    { name = "Outstanding Costume Design for a Miniseries or a Special\t1986-1997", pos = {}, },
    { name = "Outstanding Costume Design for a Regular or Limited Series\t1982-1982", pos = {}, },
    { name = "Outstanding Costume Design for a Series\t1979-1999", pos = {}, },
    { name = "Outstanding Costume Design for a Variety or Music Program\t1986-1999", pos = {}, },
    { name = "Outstanding Costumes for Variety, Nonfiction or Reality Programming\t2022-2023", pos = {}, },
    { name = "Outstanding Costumes for a Contemporary Series, Limited Series or Movie\t2015-2016", pos = {}, },
    { name = "Outstanding Costumes for a Miniseries, Movie or a Special\t2000-2014", pos = {}, },
    { name = "Outstanding Costumes for a Period/Fantasy Series, Limited Series or Movie\t2015-2016", pos = {}, },
    { name = "Outstanding Costumes for a Series\t2000-2014", pos = {}, },
    { name = "Outstanding Costumes for a Variety Program or a Special\t2012-2015", pos = {}, },
    { name = "Outstanding Costumes for a Variety or Music Program\t2000-2006", pos = {}, },
    { name = "Outstanding Costumes for a Variety, Nonfiction or Reality Program\t2016-2021", pos = {}, },
    { name = "Outstanding Costumes for a Variety/Music Program or a Special\t2008-2011", pos = {}, },
    { name = "Outstanding Costuming for a Series\t1990-1999", pos = {}, },
    { name = "Outstanding Creative Achievement in Interactive Media - Fiction\t2010-2010", pos = {}, },
    { name = "Outstanding Creative Achievement in Interactive Media - Multiplatform Storytelling\t2016-2016", pos = {}, },
    { name = "Outstanding Creative Achievement in Interactive Media - Nonfiction\t2010-2010", pos = {}, },
    { name = "Outstanding Creative Achievement in Interactive Media - Original Interactive Program\t2013-2015", pos = {}, },
    { name = "Outstanding Creative Achievement in Interactive Media - Social TV Experience\t2015-2016", pos = {}, },
    { name = "Outstanding Creative Achievement in Interactive Media within an Unscripted Program\t2018-2019", pos = {}, },
    { name = "Outstanding Cultural Music-Dance Program\t1996-1997", pos = {}, },
    { name = "Outstanding Cultural Program\t1995-1995", pos = {}, },
    { name = "Outstanding Daytime Program\t1962-1962", pos = {}, },
    { name = "Outstanding Directing for Non-Fiction Programming\t2003-2003", pos = {}, },
    { name = "Outstanding Directing for Nonfiction Programming\t2004-2017", pos = {}, },
    { name = "Outstanding Directing for a Comedy Series\t1996-2023", pos = {}, },
    { name = "Outstanding Directing for a Documentary/Nonfiction Program\t2018-2023", pos = {}, },
    { name = "Outstanding Directing for a Drama Series\t1996-2023", pos = {}, },
    { name = "Outstanding Directing for a Limited Series, Movie or Dramatic Special\t2020-2020", pos = {}, },
    { name = "Outstanding Directing for a Limited Series, Movie or a Dramatic Special\t2015-2019", pos = {}, },
    { name = "Outstanding Directing for a Limited or Anthology Series or Movie\t2021-2023", pos = {}, },
    { name = "Outstanding Directing for a Miniseries or a Movie\t1998-1999", pos = {}, },
    { name = "Outstanding Directing for a Miniseries or a Special\t1996-1997", pos = {}, },
    { name = "Outstanding Directing for a Miniseries, Movie or a Dramatic Special\t2002-2014", pos = {}, },
    { name = "Outstanding Directing for a Miniseries, Movie or a Special\t2000-2001", pos = {}, },
    { name = "Outstanding Directing for a Reality Program\t2018-2023", pos = {}, },
    { name = "Outstanding Directing for a Variety Series\t2012-2023", pos = {}, },
    { name = "Outstanding Directing for a Variety Special\t2012-2017", pos = {}, },
    { name = "Outstanding Directing for a Variety or Music Program\t1996-2001", pos = {}, },
    { name = "Outstanding Directing for a Variety, Music or Comedy Program\t2002-2008", pos = {}, },
    { name = "Outstanding Directing for a Variety, Music or Comedy Series\t2009-2011", pos = {}, },
    { name = "Outstanding Directing for a Variety, Music or Comedy Special\t2011-2011", pos = {}, },
    { name = "Outstanding Directing in Informational Programming\t1989-1989", pos = {}, },
    { name = "Outstanding Directing in a Comedy - Variety or Music Series\t1977-1977", pos = {}, },
    { name = "Outstanding Directing in a Comedy Series\t1976-1991", pos = {}, },
    { name = "Outstanding Directing in a Comedy or Comedy-Variety or Music Series\t1979-1979", pos = {}, },
    { name = "Outstanding Directing in a Comedy-Variety or Music Series\t1975-1978", pos = {}, },
    { name = "Outstanding Directing in a Drama Series\t1975-1991", pos = {}, },
    { name = "Outstanding Directing in a Limited Series or a Special\t1981-1985", pos = {}, },
    { name = "Outstanding Directing in a Miniseries or a Special\t1988-1989", pos = {}, },
    { name = "Outstanding Directing in a Special Program - Drama or Comedy\t1975-1977", pos = {}, },
    { name = "Outstanding Directing in a Variety or Music Program\t1980-1991", pos = {}, },
    { name = "Outstanding Directorial Achievement in Comedy\t1960-1973", pos = {}, },
    { name = "Outstanding Directorial Achievement in Comedy, Variety or Music\t1969-1969", pos = {}, },
    { name = "Outstanding Directorial Achievement in Drama\t1960-1968", pos = {}, },
    { name = "Outstanding Directorial Achievement in Drama - A Single Program of a Series with Continuing Characters and/or Theme\t1971-1973", pos = {}, },
    { name = "Outstanding Directorial Achievement in Music or Variety\t1968-1968", pos = {}, },
    { name = "Outstanding Directorial Achievement in Variety or Music\t1964-1973", pos = {}, },
    { name = "Outstanding Documentary or Nonfiction Series\t2013-2023", pos = {}, },
    { name = "Outstanding Documentary or Nonfiction Special\t2013-2022", pos = {}, },
    { name = "Outstanding Drama Series\t1974-2023", pos = {}, },
    { name = "Outstanding Drama Series - Continuing\t1973-1973", pos = {}, },
    { name = "Outstanding Drama Special\t1983-1983", pos = {}, },
    { name = "Outstanding Drama/Comedy - Limited Episodes\t1973-1973", pos = {}, },
    { name = "Outstanding Drama/Comedy Special\t1985-1985", pos = {}, },
    { name = "Outstanding Drama/Comedy Special and Miniseries\t1991-1991", pos = {}, },
    { name = "Outstanding Dramatic Program\t1969-1970", pos = {}, },
    { name = "Outstanding Dramatic Series\t1966-1970", pos = {}, },
    { name = "Outstanding Edited Sports Series\t1976-1976", pos = {}, },
    { name = "Outstanding Editing for a Miniseries or a Special - Multi-Camera Production\t1989-1997", pos = {}, },
    { name = "Outstanding Editing for a Miniseries or a Special - Single Camera Production\t1986-1997", pos = {}, },
    { name = "Outstanding Editing for a Series - Multi-Camera Production\t1986-1997", pos = {}, },
    { name = "Outstanding Editing for a Series - Single Camera Production\t1986-1997", pos = {}, },
    { name = "Outstanding Emerging Media Program\t2023-2023", pos = {}, },
    { name = "Outstanding Fantasy/Sci-Fi Costumes\t2018-2023", pos = {}, },
    { name = "Outstanding Film Editing for Entertainment Programming for a Series - For a Single Episode of a Comedy Series\t1975-1975", pos = {}, },
    { name = "Outstanding Film Editing for Entertainment Programming for a Series - For a Single Episode of a Drama Series\t1975-1975", pos = {}, },
    { name = "Outstanding Film Editing for Entertainment Programming for a Special\t1975-1975", pos = {}, },
    { name = "Outstanding Film Editing for a Limited Series or a Special\t1979-1985", pos = {}, },
    { name = "Outstanding Film Editing for a Series\t1979-1985", pos = {}, },
    { name = "Outstanding Film Editing for a Special\t1977-1977", pos = {}, },
    { name = "Outstanding Film Editing in a Comedy Series\t1977-1978", pos = {}, },
    { name = "Outstanding Film Editing in a Drama Series\t1977-1978", pos = {}, },
    { name = "Outstanding Film Sound Editing for a Limited Series or a Special\t1983-1984", pos = {}, },
    { name = "Outstanding Film Sound Editing for a Series\t1983-1985", pos = {}, },
    { name = "Outstanding Film Sound Mixing\t1981-1981", pos = {}, },
    { name = "Outstanding Film Sound Mixing for a Limited Series or a Special\t1983-1983", pos = {}, },
    { name = "Outstanding Film Sound Mixing for a Series\t1983-1985", pos = {}, },
    { name = "Outstanding Game Show\t2023-2023", pos = {}, },
    { name = "Outstanding Graphic Design and Title Sequences\t1981-1996", pos = {}, },
    { name = "Outstanding Graphic and Title Design\t1985-1986", pos = {}, },
    { name = "Outstanding Guest Actor in a Comedy Series\t1989-2023", pos = {}, },
    { name = "Outstanding Guest Actor in a Drama Series\t1989-2023", pos = {}, },
    { name = "Outstanding Guest Actress in a Comedy Series\t1989-2023", pos = {}, },
    { name = "Outstanding Guest Actress in a Drama Series\t1989-2023", pos = {}, },
    { name = "Outstanding Guest Performer in a Comedy Series\t1986-1988", pos = {}, },
    { name = "Outstanding Guest Performer in a Drama Series\t1986-1988", pos = {}, },
    { name = "Outstanding Hairstyling for a Limited Series or Movie\t2018-2019", pos = {}, },
    { name = "Outstanding Hairstyling for a Limited Series or a Movie\t2015-2017", pos = {}, },
    { name = "Outstanding Hairstyling for a Miniseries or a Movie\t2008-2014", pos = {}, },
    { name = "Outstanding Hairstyling for a Miniseries or a Special\t1988-1997", pos = {}, },
    { name = "Outstanding Hairstyling for a Miniseries, Movie or a Special\t1998-2007", pos = {}, },
    { name = "Outstanding Hairstyling for a Multi-Camera Series or Special\t2009-2019", pos = {}, },
    { name = "Outstanding Hairstyling for a Multi-Camera Series or a Special\t2008-2008", pos = {}, },
    { name = "Outstanding Hairstyling for a Series\t1990-2007", pos = {}, },
    { name = "Outstanding Hairstyling for a Single Camera Series\t2009-2010", pos = {}, },
    { name = "Outstanding Hairstyling for a Single-Camera Series\t2008-2019", pos = {}, },
    { name = "Outstanding Hairstyling for a Variety, Nonfiction or Reality Program\t2023-2023", pos = {}, },
    { name = "Outstanding Host For A Reality Or Reality - Competition Program\t2011-2011", pos = {}, },
    { name = "Outstanding Host for a Game Show\t2023-2023", pos = {}, },
    { name = "Outstanding Host for a Reality or Competition Program\t2022-2023", pos = {}, },
    { name = "Outstanding Host for a Reality or Reality-Competition Program\t2008-2021", pos = {}, },
    { name = "Outstanding Hosted Nonfiction Series or Special\t2020-2023", pos = {}, },
    { name = "Outstanding Individual  - Informational Programming\t1991-1991", pos = {}, },
    { name = "Outstanding Individual Achievement - Classical Music/Dance Programming\t1984-1984", pos = {}, },
    { name = "Outstanding Individual Achievement - Costumers\t1983-1984", pos = {}, },
    { name = "Outstanding Individual Achievement - Creative Special Achievement\t1982-1982", pos = {}, },
    { name = "Outstanding Individual Achievement - Creative Technical Crafts\t1979-1981", pos = {}, },
    { name = "Outstanding Individual Achievement - Cultural Programming\t1995-1995", pos = {}, },
    { name = "Outstanding Individual Achievement - Graphic Design and Title Sequences\t1982-1984", pos = {}, },
    { name = "Outstanding Individual Achievement - Informational Program\t1980-1980", pos = {}, },
    { name = "Outstanding Individual Achievement - Informational Programming\t1981-1996", pos = {}, },
    { name = "Outstanding Individual Achievement - Informational Programming - Directing\t1987-1987", pos = {}, },
    { name = "Outstanding Individual Achievement - Informational Programming - Performing\t1987-1987", pos = {}, },
    { name = "Outstanding Individual Achievement - Informational Programming - Writing\t1985-1985", pos = {}, },
    { name = "Outstanding Individual Achievement - Special Class\t1981-1982", pos = {}, },
    { name = "Outstanding Individual Achievement - Special Sound Achievement\t1984-1984", pos = {}, },
    { name = "Outstanding Individual Achievement - Special Visual Effects\t1983-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Animation\t1993-2023", pos = {}, },
    { name = "Outstanding Individual Achievement in Any Area of Creative Technical Crafts\t1976-1978", pos = {}, },
    { name = "Outstanding Individual Achievement in Art Direction for a Miniseries or a Special\t1992-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Art Direction for a Series\t1992-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Art Direction for a Variety or Music Program\t1994-1994", pos = {}, },
    { name = "Outstanding Individual Achievement in Art Direction or Scenic Design - For a Single Episode of a Comedy, Drama or Limited Series\t1975-1975", pos = {}, },
    { name = "Outstanding Individual Achievement in Casting\t1995-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Choreography\t1992-1993", pos = {}, },
    { name = "Outstanding Individual Achievement in Cinematography for a Miniseries or a Special\t1993-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Cinematography for a Series\t1993-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Costume Design for a Miniseries or a Special\t1992-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Costume Design for a Series\t1992-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Costume Design for a Variety or Music Program\t1992-1994", pos = {}, },
    { name = "Outstanding Individual Achievement in Costuming for a Miniseries or a Special\t1992-1992", pos = {}, },
    { name = "Outstanding Individual Achievement in Costuming for a Series\t1992-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Directing for a Comedy Series\t1995-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Directing for a Drama Series\t1995-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Directing for a Miniseries or a Special\t1992-1993", pos = {}, },
    { name = "Outstanding Individual Achievement in Directing for a Variety or Music Program\t1995-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Directing in a Comedy Series\t1992-1994", pos = {}, },
    { name = "Outstanding Individual Achievement in Directing in a Drama Series\t1992-1994", pos = {}, },
    { name = "Outstanding Individual Achievement in Directing in a Variety or Music Program\t1992-1994", pos = {}, },
    { name = "Outstanding Individual Achievement in Editing for a Miniseries or a Special - Single Camera Production\t1992-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Editing for a Series - Multi-Camera Production\t1992-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Editing for a Series - Single Camera Production\t1992-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Electronic Production\t1968-1969", pos = {}, },
    { name = "Outstanding Individual Achievement in Graphic Design and Title Sequences\t1992-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Hairstyling for a Miniseries or a Special\t1992-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Hairstyling for a Series\t1992-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Lighting Direction (Electronic) for a Comedy Series\t1992-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Lighting Direction (Electronic) for a Drama Series, Variety Series, Miniseries or a Special\t1992-1994", pos = {}, },
    { name = "Outstanding Individual Achievement in Main Title Theme Music\t1992-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Makeup for a Miniseries or a Special\t1992-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Makeup for a Series\t1992-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Music\t1969-1969", pos = {}, },
    { name = "Outstanding Individual Achievement in Music (Other Than Composer)\t1968-1968", pos = {}, },
    { name = "Outstanding Individual Achievement in Music Composition for a Miniseries or a Special (Dramatic Underscore)\t1993-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Music Composition for a Series (Dramatic Underscore)\t1992-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Music Direction\t1992-1993", pos = {}, },
    { name = "Outstanding Individual Achievement in Music and Lyrics\t1993-1994", pos = {}, },
    { name = "Outstanding Individual Achievement in Sound Editing for a Miniseries or a Special\t1992-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Sound Editing for a Series\t1992-1994", pos = {}, },
    { name = "Outstanding Individual Achievement in Sound Mixing for a Comedy Series or a Special\t1994-1994", pos = {}, },
    { name = "Outstanding Individual Achievement in Sound Mixing for a Drama Series\t1992-1994", pos = {}, },
    { name = "Outstanding Individual Achievement in Sound Mixing for a Variety or Music Series or a Special\t1992-1993", pos = {}, },
    { name = "Outstanding Individual Achievement in Special Musical Material\t1976-1976", pos = {}, },
    { name = "Outstanding Individual Achievement in Special Visual Effects\t1992-1994", pos = {}, },
    { name = "Outstanding Individual Achievement in Writing for a Comedy Series\t1995-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Writing for a Variety or Music Program\t1995-1995", pos = {}, },
    { name = "Outstanding Individual Achievement in Writing in a Comedy Series\t1992-1994", pos = {}, },
    { name = "Outstanding Individual Achievement in Writing in a Drama Series\t1992-1993", pos = {}, },
    { name = "Outstanding Individual Achievement in Writing in a Miniseries or a Special\t1992-1994", pos = {}, },
    { name = "Outstanding Individual Achievement in Writing in a Variety or Music Program\t1992-1994", pos = {}, },
    { name = "Outstanding Individual Achievement in the Visual Arts\t1968-1968", pos = {}, },
    { name = "Outstanding Individual Achievements - Informational Programming\t1986-1986", pos = {}, },
    { name = "Outstanding Individual Achievements in Entertainment - Actors and Performers\t1965-1965", pos = {}, },
    { name = "Outstanding Individual Achievements in Entertainment - Cinematographer\t1965-1965", pos = {}, },
    { name = "Outstanding Individual Achievements in Entertainment - Color Consultant\t1965-1965", pos = {}, },
    { name = "Outstanding Individual Achievements in Entertainment - Directors\t1965-1965", pos = {}, },
    { name = "Outstanding Individual Achievements in Entertainment - Editors\t1965-1965", pos = {}, },
    { name = "Outstanding Individual Achievements in Entertainment - Production Crew\t1965-1965", pos = {}, },
    { name = "Outstanding Individual Achievements in Entertainment - Special Photographic Effects\t1965-1965", pos = {}, },
    { name = "Outstanding Individual Achievements in Entertainment - Writers\t1965-1965", pos = {}, },
    { name = "Outstanding Individual Performance in a Variety or Music Program\t1983-2008", pos = {}, },
    { name = "Outstanding Individual in Animation\t2001-2015", pos = {}, },
    { name = "Outstanding Informational Program\t1980-1980", pos = {}, },
    { name = "Outstanding Informational Series\t1978-1997", pos = {}, },
    { name = "Outstanding Informational Series or Special\t2013-2019", pos = {}, },
    { name = "Outstanding Informational Special\t1978-1997", pos = {}, },
    { name = "Outstanding Innovation in Interactive Programming\t2021-2021", pos = {}, },
    { name = "Outstanding Interactive Extension of a Linear Program\t2020-2020", pos = {}, },
    { name = "Outstanding Interactive Program\t2014-2019", pos = {}, },
    { name = "Outstanding Lead Actor for a Single Appearance in a Drama or Comedy Series\t1976-1978", pos = {}, },
    { name = "Outstanding Lead Actor in a Comedy Series\t1975-2023", pos = {}, },
    { name = "Outstanding Lead Actor in a Drama Series\t1975-2023", pos = {}, },
    { name = "Outstanding Lead Actor in a Drama or Comedy Special\t1976-1976", pos = {}, },
    { name = "Outstanding Lead Actor in a Limited Series\t1975-1978", pos = {}, },
    { name = "Outstanding Lead Actor in a Limited Series or Movie\t2017-2020", pos = {}, },
    { name = "Outstanding Lead Actor in a Limited Series or a Movie\t2015-2016", pos = {}, },
    { name = "Outstanding Lead Actor in a Limited Series or a Special\t1979-1983", pos = {}, },
    { name = "Outstanding Lead Actor in a Limited or Anthology Series or Movie\t2021-2023", pos = {}, },
    { name = "Outstanding Lead Actor in a Miniseries or Movie\t2007-2011", pos = {}, },
    { name = "Outstanding Lead Actor in a Miniseries or a Movie\t1998-2014", pos = {}, },
    { name = "Outstanding Lead Actor in a Miniseries or a Special\t1988-1994", pos = {}, },
    { name = "Outstanding Lead Actress for a Single Appearance in a Drama or Comedy Series\t1976-1978", pos = {}, },
    { name = "Outstanding Lead Actress in a Comedy Series\t1975-2023", pos = {}, },
    { name = "Outstanding Lead Actress in a Drama Series\t1975-2023", pos = {}, },
    { name = "Outstanding Lead Actress in a Drama or Comedy Special\t1976-1977", pos = {}, },
    { name = "Outstanding Lead Actress in a Limited Series\t1975-1978", pos = {}, },
    { name = "Outstanding Lead Actress in a Limited Series or Movie\t2017-2020", pos = {}, },
    { name = "Outstanding Lead Actress in a Limited Series or a Movie\t2015-2016", pos = {}, },
    { name = "Outstanding Lead Actress in a Limited Series or a Special\t1979-1985", pos = {}, },
    { name = "Outstanding Lead Actress in a Limited or Anthology Series or Movie\t2021-2023", pos = {}, },
    { name = "Outstanding Lead Actress in a Miniseries or Movie\t2007-2011", pos = {}, },
    { name = "Outstanding Lead Actress in a Miniseries or a Movie\t1998-2014", pos = {}, },
    { name = "Outstanding Lead Actress in a Miniseries or a Special\t1987-1997", pos = {}, },
    { name = "Outstanding Lighting Design or Lighting Direction for a Variety, Music, or Comedy Series\t2011-2011", pos = {}, },
    { name = "Outstanding Lighting Design/Lighting Direction for a Variety Series\t2012-2023", pos = {}, },
    { name = "Outstanding Lighting Design/Lighting Direction for a Variety Special\t2012-2015", pos = {}, },
    { name = "Outstanding Lighting Direction (Electronic)\t1982-2000", pos = {}, },
    { name = "Outstanding Lighting Direction (Electronic) for a Comedy Series\t1988-1999", pos = {}, },
    { name = "Outstanding Lighting Direction (Electronic) for a Drama Series, Variety Series, Miniseries or a Special\t1989-1997", pos = {}, },
    { name = "Outstanding Lighting Direction (Electronic) for a Drama Series, Variety Series, Miniseries, Movie or a Special\t1998-1998", pos = {}, },
    { name = "Outstanding Lighting Direction (Electronic) for a Limited Series or a Special\t1983-1983", pos = {}, },
    { name = "Outstanding Lighting Direction (Electronic) for a Series\t1983-1987", pos = {}, },
    { name = "Outstanding Lighting Direction (Electronic, Multi-Camera) for VMC Programming\t2005-2008", pos = {}, },
    { name = "Outstanding Lighting Direction (Electronic, Multi-Camera) for Variety, Music or Comedy Programming\t2009-2009", pos = {}, },
    { name = "Outstanding Lighting Direction (Electronic, Multi-Camera) for Vmc Programming\t2007-2007", pos = {}, },
    { name = "Outstanding Lighting Direction (Electronic, Multi-Camera) for a VMC Programming\t2004-2004", pos = {}, },
    { name = "Outstanding Lighting Direction (Electronic, Multicamera) for VMC Programming\t2001-2001", pos = {}, },
    { name = "Outstanding Limited Series\t1974-2020", pos = {}, },
    { name = "Outstanding Limited or Anthology Series\t2021-2023", pos = {}, },
    { name = "Outstanding Live Sports Series\t1976-1976", pos = {}, },
    { name = "Outstanding Live and Tape Sound Mixing and Sound Effects for a Series\t1984-1985", pos = {}, },
    { name = "Outstanding Made for Television Movie\t1992-2008", pos = {}, },
    { name = "Outstanding Main Title Design\t1997-2023", pos = {}, },
    { name = "Outstanding Main Title Theme Music\t1990-2005", pos = {}, },
    { name = "Outstanding Makeup for a Limited Series or Movie (Non-Prosthetic)\t2017-2019", pos = {}, },
    { name = "Outstanding Makeup for a Limited Series or a Movie (Non-Prosthetic)\t2015-2016", pos = {}, },
    { name = "Outstanding Makeup for a Miniseries or a Movie (Non-Prosthetic)\t2008-2014", pos = {}, },
    { name = "Outstanding Makeup for a Miniseries or a Special\t1990-1997", pos = {}, },
    { name = "Outstanding Makeup for a Miniseries, Movie or a Special\t1998-2001", pos = {}, },
    { name = "Outstanding Makeup for a Miniseries, Movie or a Special (Non-Prosthetic)\t2002-2007", pos = {}, },
    { name = "Outstanding Makeup for a Miniseries, Movie or a Special (Prosthetic)\t2002-2003", pos = {}, },
    { name = "Outstanding Makeup for a Multi-Camera Series or Special (Non-Prosthetic)\t2012-2019", pos = {}, },
    { name = "Outstanding Makeup for a Multi-Camera Series or Special (Non-prosthetic)\t2009-2010", pos = {}, },
    { name = "Outstanding Makeup for a Multi-Camera Series or a Special (Non-Prosthetic)\t2008-2018", pos = {}, },
    { name = "Outstanding Makeup for a Series\t1987-2001", pos = {}, },
    { name = "Outstanding Makeup for a Series (Non-Prosthetic)\t2002-2007", pos = {}, },
    { name = "Outstanding Makeup for a Series (Prosthetic)\t2002-2003", pos = {}, },
    { name = "Outstanding Makeup for a Series, Miniseries, Movie or a Special (Prosthetic)\t2004-2004", pos = {}, },
    { name = "Outstanding Makeup for a Single Camera Series (Non-prosthetic)\t2009-2009", pos = {}, },
    { name = "Outstanding Makeup for a Single-Camera Series (Non-Prosthetic)\t2008-2019", pos = {}, },
    { name = "Outstanding Makeup for a Variety, Nonfiction or Reality Program\t2022-2022", pos = {}, },
    { name = "Outstanding Miniseries\t1986-2014", pos = {}, },
    { name = "Outstanding Miniseries or Movie\t2011-2013", pos = {}, },
    { name = "Outstanding Motion Design\t2018-2023", pos = {}, },
    { name = "Outstanding Multi-Camera Picture Editing for a Comedy Series\t2012-2022", pos = {}, },
    { name = "Outstanding Multi-Camera Picture Editing for a Series\t1998-2007", pos = {}, },
    { name = "Outstanding Multi-Camera Sound Mixing for a Series or Special\t2002-2006", pos = {}, },
    { name = "Outstanding Multi-Camera Sound Mixing for a Series or a Special\t2001-2001", pos = {}, },
    { name = "Outstanding Music Composition for a Documentary Series or Special (Original Dramatic Score)\t2019-2023", pos = {}, },
    { name = "Outstanding Music Composition for a Limited Series, Movie or Special (Original Dramatic Score)\t2018-2020", pos = {}, },
    { name = "Outstanding Music Composition for a Limited Series, Movie or a Special (Original Dramatic Score)\t2015-2016", pos = {}, },
    { name = "Outstanding Music Composition for a Limited Series, Movie, or Special (Original Dramatic Score)\t2017-2019", pos = {}, },
    { name = "Outstanding Music Composition for a Limited or Anthology Series, Movie or Special (Original Dramatic Score)\t2021-2023", pos = {}, },
    { name = "Outstanding Music Composition for a Miniseries or a Movie (Dramatic Underscore)\t1998-1998", pos = {}, },
    { name = "Outstanding Music Composition for a Miniseries or a Special\t1996-1996", pos = {}, },
    { name = "Outstanding Music Composition for a Miniseries or a Special (Dramatic Underscore)\t1988-1997", pos = {}, },
    { name = "Outstanding Music Composition for a Miniseries, Movie or a Special\t2000-2010", pos = {}, },
    { name = "Outstanding Music Composition for a Miniseries, Movie or a Special (Dramatic Underscore)\t2002-2005", pos = {}, },
    { name = "Outstanding Music Composition for a Miniseries, Movie or a Special (Original Dramatic Score)\t2006-2014", pos = {}, },
    { name = "Outstanding Music Composition for a Series\t1979-1996", pos = {}, },
    { name = "Outstanding Music Composition for a Series (Dramatic Underscore)\t1980-2005", pos = {}, },
    { name = "Outstanding Music Composition for a Series (Original Dramatic Score)\t2006-2023", pos = {}, },
    { name = "Outstanding Music Direction\t1998-2023", pos = {}, },
    { name = "Outstanding Music Supervision\t2017-2023", pos = {}, },
    { name = "Outstanding Music and Lyrics\t1990-2005", pos = {}, },
    { name = "Outstanding Music-Variety Series\t1974-1974", pos = {}, },
    { name = "Outstanding Musical or Variety Program\t1968-1968", pos = {}, },
    { name = "Outstanding Musical or Variety Series\t1968-1968", pos = {}, },
    { name = "Outstanding Narrator\t2014-2023", pos = {}, },
    { name = "Outstanding New Series\t1970-1973", pos = {}, },
    { name = "Outstanding Non-Fiction Program (Alternative)\t2003-2003", pos = {}, },
    { name = "Outstanding Non-Fiction Program (Reality)\t2001-2002", pos = {}, },
    { name = "Outstanding Non-Fiction Program (Special Class)\t2001-2001", pos = {}, },
    { name = "Outstanding Non-Fiction Series\t1998-2001", pos = {}, },
    { name = "Outstanding Non-Fiction Series (Informational)\t2002-2002", pos = {}, },
    { name = "Outstanding Non-Fiction Series (Traditional)\t2003-2003", pos = {}, },
    { name = "Outstanding Non-Fiction Special\t1991-1998", pos = {}, },
    { name = "Outstanding Non-Fiction Special (Informational)\t2002-2002", pos = {}, },
    { name = "Outstanding Nonfiction Series\t2004-2012", pos = {}, },
    { name = "Outstanding Nonfiction Special\t2005-2006", pos = {}, },
    { name = "Outstanding Original Interactive Program\t2019-2019", pos = {}, },
    { name = "Outstanding Original Main Title Theme Music\t2006-2023", pos = {}, },
    { name = "Outstanding Original Music and Lyrics\t2006-2023", pos = {}, },
    { name = "Outstanding Performance by a Supporting Actor in a Comedy or Drama Special\t1978-1978", pos = {}, },
    { name = "Outstanding Performance by an Actor in a Series (Lead or Support)\t1960-1960", pos = {}, },
    { name = "Outstanding Performance by an Actor in a Series (Lead)\t1961-1961", pos = {}, },
    { name = "Outstanding Performance by an Actor in a Supporting Role in Comedy\t1970-1973", pos = {}, },
    { name = "Outstanding Performance by an Actor in a Supporting Role in Drama\t1970-1973", pos = {}, },
    { name = "Outstanding Performance by an Actor in a Supporting Role in a Comedy\t1966-1968", pos = {}, },
    { name = "Outstanding Performance by an Actor in a Supporting Role in a Drama\t1966-1968", pos = {}, },
    { name = "Outstanding Performance by an Actress in a Series (Lead or Support)\t1960-1960", pos = {}, },
    { name = "Outstanding Performance by an Actress in a Series (Lead)\t1961-1961", pos = {}, },
    { name = "Outstanding Performance by an Actress in a Supporting Role in Comedy\t1970-1973", pos = {}, },
    { name = "Outstanding Performance by an Actress in a Supporting Role in Drama\t1970-1973", pos = {}, },
    { name = "Outstanding Performance by an Actress in a Supporting Role in a Comedy\t1966-1968", pos = {}, },
    { name = "Outstanding Performance by an Actress in a Supporting Role in a Drama\t1966-1968", pos = {}, },
    { name = "Outstanding Performance in a Supporting Role by an Actor\t1962-1964", pos = {}, },
    { name = "Outstanding Performance in a Supporting Role by an Actor or Actress in a Series\t1961-1961", pos = {}, },
    { name = "Outstanding Performance in a Supporting Role by an Actor or Actress in a Single Program\t1961-1961", pos = {}, },
    { name = "Outstanding Performance in a Supporting Role by an Actress\t1962-1964", pos = {}, },
    { name = "Outstanding Performance in a Variety or Music Program\t1997-1999", pos = {}, },
    { name = "Outstanding Performance in a Variety or Musical Program or Series\t1960-1964", pos = {}, },
    { name = "Outstanding Period Costumes\t2018-2022", pos = {}, },
    { name = "Outstanding Period Costumes for a Limited or Anthology Series or Movie\t2023-2023", pos = {}, },
    { name = "Outstanding Period Costumes for a Series\t2023-2023", pos = {}, },
    { name = "Outstanding Period and/or Character Hairstyling\t2020-2023", pos = {}, },
    { name = "Outstanding Period and/or Character Makeup (Non-Prosthetic)\t2020-2023", pos = {}, },
    { name = "Outstanding Period/Fantasy Costumes for a Series, Limited Series, or Movie\t2017-2017", pos = {}, },
    { name = "Outstanding Picture Editing for Non-Fiction Programming\t2001-2001", pos = {}, },
    { name = "Outstanding Picture Editing for Non-Fiction Programming (Single or Multi-Camera)\t2002-2003", pos = {}, },
    { name = "Outstanding Picture Editing for Nonfiction Programming\t2007-2018", pos = {}, },
    { name = "Outstanding Picture Editing for Nonfiction Programming (Large Team Entries - Primarily Multi-Camera Productions)\t2006-2006", pos = {}, },
    { name = "Outstanding Picture Editing for Nonfiction Programming (Single or Multi-Camera)\t2004-2005", pos = {}, },
    { name = "Outstanding Picture Editing for Nonfiction Programming (Small Team Entries - Primarily Single-Camera Productions)\t2006-2006", pos = {}, },
    { name = "Outstanding Picture Editing for Reality Programming\t2007-2015", pos = {}, },
    { name = "Outstanding Picture Editing for Short-Form Segments and Variety Specials\t2012-2014", pos = {}, },
    { name = "Outstanding Picture Editing for Variety Programming\t2015-2023", pos = {}, },
    { name = "Outstanding Picture Editing for a Comedy Series (Single or Multi-Camera)\t2008-2011", pos = {}, },
    { name = "Outstanding Picture Editing for a Drama Series\t2023-2023", pos = {}, },
    { name = "Outstanding Picture Editing for a Limited or Anthology Series or Movie\t2023-2023", pos = {}, },
    { name = "Outstanding Picture Editing for a Multi-Camera Comedy Series\t2023-2023", pos = {}, },
    { name = "Outstanding Picture Editing for a Nonfiction Program\t2016-2023", pos = {}, },
    { name = "Outstanding Picture Editing for a Single-Camera Comedy Series\t2023-2023", pos = {}, },
    { name = "Outstanding Picture Editing for a Special (Single or Multi-Camera)\t2005-2008", pos = {}, },
    { name = "Outstanding Picture Editing for a Structured Reality or Competition Program\t2019-2023", pos = {}, },
    { name = "Outstanding Picture Editing for a Structured or Competition Reality Program\t2016-2019", pos = {}, },
    { name = "Outstanding Picture Editing for an Unstructured Reality Program\t2016-2023", pos = {}, },
    { name = "Outstanding Picture Editing in Non-Fiction Program\t2000-2000", pos = {}, },
    { name = "Outstanding Picture Editing of Clip Packages for Talk, Performance, Award or a Reality-Competition Program\t2008-2008", pos = {}, },
    { name = "Outstanding Production Design for Variety, Nonfiction, Event or Award Special\t2017-2017", pos = {}, },
    { name = "Outstanding Production Design for Variety, Nonfiction, Reality or Reality-Competition Programming\t2015-2017", pos = {}, },
    { name = "Outstanding Production Design for Variety, Nonfiction, Reality or Reality-Competition Series\t2016-2018", pos = {}, },
    { name = "Outstanding Production Design for a Narrative Contemporary Program (One Hour or More)\t2018-2023", pos = {}, },
    { name = "Outstanding Production Design for a Narrative Contemporary or Fantasy Program (One Hour or More)\t2015-2017", pos = {}, },
    { name = "Outstanding Production Design for a Narrative Period Program (One Hour or More)\t2015-2017", pos = {}, },
    { name = "Outstanding Production Design for a Narrative Period or Fantasy Program (One Hour or More)\t2018-2023", pos = {}, },
    { name = "Outstanding Production Design for a Narrative Program (Half-Hour or Less)\t2015-2018", pos = {}, },
    { name = "Outstanding Production Design for a Narrative Program (Half-Hour)\t2019-2023", pos = {}, },
    { name = "Outstanding Production Design for a Variety or Reality Series\t2023-2023", pos = {}, },
    { name = "Outstanding Production Design for a Variety, Reality or Competition Series\t2019-2022", pos = {}, },
    { name = "Outstanding Program Achievement - Special Class\t1979-1980", pos = {}, },
    { name = "Outstanding Program Achievement in Daytime\t1973-1973", pos = {}, },
    { name = "Outstanding Program Achievement in Daytime Drama\t1973-1973", pos = {}, },
    { name = "Outstanding Program Achievement in the Field of Children's Programming\t1962-1964", pos = {}, },
    { name = "Outstanding Program Achievement in the Field of Comedy\t1964-1964", pos = {}, },
    { name = "Outstanding Program Achievement in the Field of Drama\t1960-1964", pos = {}, },
    { name = "Outstanding Program Achievement in the Field of Educational and Public Affairs Programming\t1962-1962", pos = {}, },
    { name = "Outstanding Program Achievement in the Field of Humor\t1960-1963", pos = {}, },
    { name = "Outstanding Program Achievement in the Field of News Reports\t1964-1964", pos = {}, },
    { name = "Outstanding Program Achievement in the Field of Panel, Quiz or Audience Participation\t1963-1963", pos = {}, },
    { name = "Outstanding Program Achievement in the Field of Public Affairs and Education\t1960-1960", pos = {}, },
    { name = "Outstanding Program Achievement in the Field of Variety\t1960-1964", pos = {}, },
    { name = "Outstanding Program Achievements in Entertainment\t1965-1965", pos = {}, },
    { name = "Outstanding Program Achievements in the Fields of Variety and Music - Variety\t1962-1962", pos = {}, },
    { name = "Outstanding Prosthetic Makeup\t2021-2023", pos = {}, },
    { name = "Outstanding Prosthetic Makeup for a Series, Limited Series, Movie or Special\t2018-2020", pos = {}, },
    { name = "Outstanding Prosthetic Makeup for a Series, Limited Series, Movie or a Special\t2015-2017", pos = {}, },
    { name = "Outstanding Prosthetic Makeup for a Series, Miniseries, Movie or a Special\t2005-2014", pos = {}, },
    { name = "Outstanding Reality - Competition Program\t2009-2011", pos = {}, },
    { name = "Outstanding Reality Competition Program\t2016-2023", pos = {}, },
    { name = "Outstanding Reality Program\t2004-2013", pos = {}, },
    { name = "Outstanding Reality-Competition Program\t2004-2019", pos = {}, },
    { name = "Outstanding Scripted Variety Series\t2023-2023", pos = {}, },
    { name = "Outstanding Series - Comedy\t1971-1972", pos = {}, },
    { name = "Outstanding Series - Drama\t1971-1972", pos = {}, },
    { name = "Outstanding Short Form Animated Program\t2016-2022", pos = {}, },
    { name = "Outstanding Short Form Comedy or Drama Series\t2016-2020", pos = {}, },
    { name = "Outstanding Short Form Comedy, Drama or Variety Series\t2021-2023", pos = {}, },
    { name = "Outstanding Short Form Nonfiction or Reality Series\t2016-2023", pos = {}, },
    { name = "Outstanding Short Form Picture Editing\t2009-2009", pos = {}, },
    { name = "Outstanding Short Form Variety Series\t2016-2020", pos = {}, },
    { name = "Outstanding Short-Form Picture Editing\t2010-2011", pos = {}, },
    { name = "Outstanding Short-Format Animated Program\t2010-2015", pos = {}, },
    { name = "Outstanding Short-Format Live-Action Entertainment Program\t2014-2015", pos = {}, },
    { name = "Outstanding Short-Format Nonfiction Program\t2014-2014", pos = {}, },
    { name = "Outstanding Single Camera Picture Editing for a Comedy Series\t2003-2007", pos = {}, },
    { name = "Outstanding Single Camera Picture Editing for a Drama Series\t2003-2016", pos = {}, },
    { name = "Outstanding Single Camera Picture Editing for a Miniseries or a Movie\t1998-2010", pos = {}, },
    { name = "Outstanding Single Camera Picture Editing for a Miniseries, Movie or a Special\t2000-2003", pos = {}, },
    { name = "Outstanding Single Camera Picture Editing for a Series\t1998-2002", pos = {}, },
    { name = "Outstanding Single Camera Sound Mixing for a Miniseries or a Movie\t2001-2003", pos = {}, },
    { name = "Outstanding Single Camera Sound Mixing for a Series\t2001-2003", pos = {}, },
    { name = "Outstanding Single Performance by a Supporting Actor in Comedy or Drama Series\t1976-1976", pos = {}, },
    { name = "Outstanding Single Performance by a Supporting Actor in a Comedy or Drama Series\t1975-1978", pos = {}, },
    { name = "Outstanding Single Performance by a Supporting Actor in a Comedy or Drama Special\t1975-1975", pos = {}, },
    { name = "Outstanding Single Performance by a Supporting Actress in Comedy or Drama Series\t1976-1976", pos = {}, },
    { name = "Outstanding Single Performance by a Supporting Actress in Comedy or Drama Special\t1976-1976", pos = {}, },
    { name = "Outstanding Single Performance by a Supporting Actress in a Comedy or Drama Series\t1975-1978", pos = {}, },
    { name = "Outstanding Single Performance by a Supporting Actress in a Comedy or Drama Special\t1975-1975", pos = {}, },
    { name = "Outstanding Single Performance by an Actor (Lead or Support)\t1960-1960", pos = {}, },
    { name = "Outstanding Single Performance by an Actor in a Leading Role\t1961-1972", pos = {}, },
    { name = "Outstanding Single Performance by an Actor in a Leading Role in a Drama\t1966-1966", pos = {}, },
    { name = "Outstanding Single Performance by an Actor in a Supporting Role\t1969-1969", pos = {}, },
    { name = "Outstanding Single Performance by an Actress (Lead or Support)\t1960-1960", pos = {}, },
    { name = "Outstanding Single Performance by an Actress in a Leading Role\t1961-1972", pos = {}, },
    { name = "Outstanding Single Performance by an Actress in a Leading Role in a Drama\t1966-1966", pos = {}, },
    { name = "Outstanding Single Performance by an Actress in a Supporting Role\t1969-1969", pos = {}, },
    { name = "Outstanding Single Program - Drama or Comedy\t1971-1972", pos = {}, },
    { name = "Outstanding Single Program - Variety or Musical - Variety and Popular Music\t1972-1972", pos = {}, },
    { name = "Outstanding Single-Camera Picture Editing for a Comedy Series\t2004-2022", pos = {}, },
    { name = "Outstanding Single-Camera Picture Editing for a Drama Series\t2004-2022", pos = {}, },
    { name = "Outstanding Single-Camera Picture Editing for a Limited Series or Movie\t2018-2020", pos = {}, },
    { name = "Outstanding Single-Camera Picture Editing for a Limited Series or a Movie\t2015-2017", pos = {}, },
    { name = "Outstanding Single-Camera Picture Editing for a Limited or Anthology Series or Movie\t2021-2022", pos = {}, },
    { name = "Outstanding Single-Camera Picture Editing for a Miniseries or a Movie\t2005-2014", pos = {}, },
    { name = "Outstanding Single-Camera Picture Editing for a Miniseries, Movie or a Special\t2004-2004", pos = {}, },
    { name = "Outstanding Single-Camera Sound Mixing for a Miniseries or a Movie\t2004-2006", pos = {}, },
    { name = "Outstanding Single-Camera Sound Mixing for a Series\t2004-2006", pos = {}, },
    { name = "Outstanding Sound Editing For a Comedy or Drama Series (Half-Hour) and Animation\t2019-2019", pos = {}, },
    { name = "Outstanding Sound Editing for Non-Fiction Programming (Single or Multi-Camera)\t2002-2003", pos = {}, },
    { name = "Outstanding Sound Editing for Nonfiction Program (Single or Multi-Camera)\t2019-2019", pos = {}, },
    { name = "Outstanding Sound Editing for Nonfiction Programming (Single or Multi-Camera)\t2004-2017", pos = {}, },
    { name = "Outstanding Sound Editing for a Comedy or Drama Series (Half-Hour) and Animation\t2018-2023", pos = {}, },
    { name = "Outstanding Sound Editing for a Comedy or Drama Series (One Hour)\t2018-2023", pos = {}, },
    { name = "Outstanding Sound Editing for a Limited Series, Movie or Special\t2016-2020", pos = {}, },
    { name = "Outstanding Sound Editing for a Limited Series, Movie or a Special\t2015-2015", pos = {}, },
    { name = "Outstanding Sound Editing for a Limited or Anthology Series, Movie or Special\t2021-2023", pos = {}, },
    { name = "Outstanding Sound Editing for a Miniseries or a Special\t1986-1997", pos = {}, },
    { name = "Outstanding Sound Editing for a Miniseries, Movie or a Special\t1998-2014", pos = {}, },
    { name = "Outstanding Sound Editing for a Non-Fiction Program\t2001-2001", pos = {}, },
    { name = "Outstanding Sound Editing for a Nonfiction Program (Single or Multi-Camera)\t2016-2018", pos = {}, },
    { name = "Outstanding Sound Editing for a Nonfiction or Reality Program (Single or Multi-Camera)\t2020-2023", pos = {}, },
    { name = "Outstanding Sound Editing for a Series\t1983-2017", pos = {}, },
    { name = "Outstanding Sound Editing in Non-Fiction Program\t2000-2000", pos = {}, },
    { name = "Outstanding Sound Mixing for Non-Fiction Programming (Single or Multi-Camera)\t2002-2003", pos = {}, },
    { name = "Outstanding Sound Mixing for Nonfiction Programming\t2009-2015", pos = {}, },
    { name = "Outstanding Sound Mixing for Nonfiction Programming (Single or Multi-Camera)\t2004-2017", pos = {}, },
    { name = "Outstanding Sound Mixing for a Comedy Series or a Special\t1986-2000", pos = {}, },
    { name = "Outstanding Sound Mixing for a Comedy or Drama Series (Half-Hour) And Animation\t2007-2010", pos = {}, },
    { name = "Outstanding Sound Mixing for a Comedy or Drama Series (Half-Hour) and Animation\t2008-2023", pos = {}, },
    { name = "Outstanding Sound Mixing for a Comedy or Drama Series (One Hour)\t2008-2023", pos = {}, },
    { name = "Outstanding Sound Mixing for a Comedy or Drama Series (One-Hour)\t2007-2012", pos = {}, },
    { name = "Outstanding Sound Mixing for a Drama Miniseries or a Movie\t1998-1998", pos = {}, },
    { name = "Outstanding Sound Mixing for a Drama Miniseries or a Special\t1987-1997", pos = {}, },
    { name = "Outstanding Sound Mixing for a Drama Series\t1986-2000", pos = {}, },
    { name = "Outstanding Sound Mixing for a Limited Series or Movie\t2016-2020", pos = {}, },
    { name = "Outstanding Sound Mixing for a Limited Series or a Movie\t2015-2015", pos = {}, },
    { name = "Outstanding Sound Mixing for a Limited or Anthology Series or Movie\t2021-2023", pos = {}, },
    { name = "Outstanding Sound Mixing for a Miniseries or a Movie\t1999-2014", pos = {}, },
    { name = "Outstanding Sound Mixing for a Miniseries or a Special\t1986-1989", pos = {}, },
    { name = "Outstanding Sound Mixing for a Non-Fiction Program\t2001-2001", pos = {}, },
    { name = "Outstanding Sound Mixing for a Nonfiction Program (Single or Multi-Camera)\t2016-2023", pos = {}, },
    { name = "Outstanding Sound Mixing for a Nonfiction or Reality Program (Single or Multi-Camera)\t2020-2022", pos = {}, },
    { name = "Outstanding Sound Mixing for a Reality Program (Single or Multi-Camera)\t2023-2023", pos = {}, },
    { name = "Outstanding Sound Mixing for a Variety Series or Special\t2012-2023", pos = {}, },
    { name = "Outstanding Sound Mixing for a Variety or Music Series or Special\t2001-2011", pos = {}, },
    { name = "Outstanding Sound Mixing for a Variety or Music Series or Special or Animation\t2005-2005", pos = {}, },
    { name = "Outstanding Sound Mixing for a Variety or Music Series or a Special\t1986-1997", pos = {}, },
    { name = "Outstanding Sound Mixing for a Variety, Music Series or a Special\t2008-2008", pos = {}, },
    { name = "Outstanding Special - Drama or Comedy\t1975-1978", pos = {}, },
    { name = "Outstanding Special Class - Classical Music/Dance Programs\t2008-2008", pos = {}, },
    { name = "Outstanding Special Class - Short-Format Animated Programs\t2008-2009", pos = {}, },
    { name = "Outstanding Special Class - Short-Format Live-Action Entertainment Programs\t2008-2013", pos = {}, },
    { name = "Outstanding Special Class - Short-Format Nonfiction Programs\t2013-2013", pos = {}, },
    { name = "Outstanding Special Class Program\t2002-2015", pos = {}, },
    { name = "Outstanding Special Class Programs\t2009-2013", pos = {}, },
    { name = "Outstanding Special Visual Effects\t1985-2020", pos = {}, },
    { name = "Outstanding Special Visual Effects for a Miniseries or a Movie\t1998-1999", pos = {}, },
    { name = "Outstanding Special Visual Effects for a Miniseries, Movie or a Special\t2000-2011", pos = {}, },
    { name = "Outstanding Special Visual Effects for a Series\t1998-2011", pos = {}, },
    { name = "Outstanding Special Visual Effects in a Season or a Movie\t2021-2023", pos = {}, },
    { name = "Outstanding Special Visual Effects in a Single Episode\t2021-2023", pos = {}, },
    { name = "Outstanding Special Visual Effects in a Supporting Role\t2012-2020", pos = {}, },
    { name = "Outstanding Special and Visual Effects\t2014-2014", pos = {}, },
    { name = "Outstanding Special and Visual Effects in a Supporting Role\t2014-2014", pos = {}, },
    { name = "Outstanding Sports Personality\t1976-1976", pos = {}, },
    { name = "Outstanding Structured Reality Program\t2014-2023", pos = {}, },
    { name = "Outstanding Stunt Coordination\t2002-2021", pos = {}, },
    { name = "Outstanding Stunt Coordination for a Comedy Series or a Variety Program\t2013-2023", pos = {}, },
    { name = "Outstanding Stunt Coordination for a Drama Series, Limited Series or Movie\t2015-2020", pos = {}, },
    { name = "Outstanding Stunt Coordination for a Drama Series, Limited or Anthology Series or Movie\t2022-2023", pos = {}, },
    { name = "Outstanding Stunt Coordination for a Drama Series, Miniseries or Movie\t2013-2014", pos = {}, },
    { name = "Outstanding Stunt Performance\t2021-2023", pos = {}, },
    { name = "Outstanding Supporting Actor in a Comedy Series\t1984-2023", pos = {}, },
    { name = "Outstanding Supporting Actor in a Comedy or Comedy-Variety or Music Series\t1979-1979", pos = {}, },
    { name = "Outstanding Supporting Actor in a Comedy or Variety or Music Series\t1980-1982", pos = {}, },
    { name = "Outstanding Supporting Actor in a Comedy, Variety or Music Series\t1983-1983", pos = {}, },
    { name = "Outstanding Supporting Actor in a Drama Series\t1979-2023", pos = {}, },
    { name = "Outstanding Supporting Actor in a Limited Series or Movie\t2017-2020", pos = {}, },
    { name = "Outstanding Supporting Actor in a Limited Series or a Movie\t2015-2016", pos = {}, },
    { name = "Outstanding Supporting Actor in a Limited Series or a Special\t1979-1985", pos = {}, },
    { name = "Outstanding Supporting Actor in a Limited or Anthology Series or Movie\t2021-2023", pos = {}, },
    { name = "Outstanding Supporting Actor in a Miniseries or Movie\t2007-2011", pos = {}, },
    { name = "Outstanding Supporting Actor in a Miniseries or a Movie\t1998-2014", pos = {}, },
    { name = "Outstanding Supporting Actor in a Miniseries or a Special\t1987-1997", pos = {}, },
    { name = "Outstanding Supporting Actress in a Comedy Series\t1984-2023", pos = {}, },
    { name = "Outstanding Supporting Actress in a Comedy or Comedy-Variety or Music Series\t1979-1979", pos = {}, },
    { name = "Outstanding Supporting Actress in a Comedy or Variety or Music Series\t1980-1982", pos = {}, },
    { name = "Outstanding Supporting Actress in a Comedy, Variety or Music Series\t1983-1983", pos = {}, },
    { name = "Outstanding Supporting Actress in a Drama Series\t1979-2023", pos = {}, },
    { name = "Outstanding Supporting Actress in a Limited Series or Movie\t2017-2020", pos = {}, },
    { name = "Outstanding Supporting Actress in a Limited Series or a Movie\t2015-2016", pos = {}, },
    { name = "Outstanding Supporting Actress in a Limited Series or a Special\t1979-1985", pos = {}, },
    { name = "Outstanding Supporting Actress in a Limited or Anthology Series or Movie\t2021-2023", pos = {}, },
    { name = "Outstanding Supporting Actress in a Miniseries or Movie\t2007-2011", pos = {}, },
    { name = "Outstanding Supporting Actress in a Miniseries or a Movie\t1998-2014", pos = {}, },
    { name = "Outstanding Supporting Actress in a Miniseries or a Special\t1986-1997", pos = {}, },
    { name = "Outstanding Talk Series\t2023-2023", pos = {}, },
    { name = "Outstanding Tape Sound Mixing for a Series\t1983-1983", pos = {}, },
    { name = "Outstanding Technical Direction and Camerawork for a Series\t2023-2023", pos = {}, },
    { name = "Outstanding Technical Direction and Electronic Camerawork for a Series\t1983-1983", pos = {}, },
    { name = "Outstanding Technical Direction, Camerawork, Video Control for a Miniseries, Movie or a Special\t2011-2012", pos = {}, },
    { name = "Outstanding Technical Direction, Camerawork, Video Control for a Series\t2009-2022", pos = {}, },
    { name = "Outstanding Technical Direction, Camerawork, Video for a Miniseries, Movie or a Special\t2005-2008", pos = {}, },
    { name = "Outstanding Technical Direction, Camerawork, Video for a Series\t2000-2008", pos = {}, },
    { name = "Outstanding Technical Direction/Camera/Video for a Miniseries or a Special\t1989-1997", pos = {}, },
    { name = "Outstanding Technical Direction/Camera/Video for a Series\t1989-1999", pos = {}, },
    { name = "Outstanding Technical Direction/Camerawork/Video for a Series\t1984-1984", pos = {}, },
    { name = "Outstanding Technical Direction/Electronic Camera/Video Control for a Limited Series or a Special\t1985-1985", pos = {}, },
    { name = "Outstanding Technical Direction/Electronic Camerawork/Video Control for a Series\t1985-1988", pos = {}, },
    { name = "Outstanding Television Movie\t2014-2020", pos = {}, },
    { name = "Outstanding Unstructured Reality Program\t2014-2023", pos = {}, },
    { name = "Outstanding Variety Musical Series\t1973-1973", pos = {}, },
    { name = "Outstanding Variety Series\t1966-2014", pos = {}, },
    { name = "Outstanding Variety Series - Musical\t1971-1972", pos = {}, },
    { name = "Outstanding Variety Series - Talk\t1971-1972", pos = {}, },
    { name = "Outstanding Variety Sketch Series\t2015-2022", pos = {}, },
    { name = "Outstanding Variety Special\t1966-2017", pos = {}, },
    { name = "Outstanding Variety Special (Pre-Recorded)\t2018-2018", pos = {}, },
    { name = "Outstanding Variety Talk Series\t2015-2022", pos = {}, },
    { name = "Outstanding Variety or Music Program\t1980-1980", pos = {}, },
    { name = "Outstanding Variety or Musical Program\t1969-1969", pos = {}, },
    { name = "Outstanding Variety or Musical Series\t1969-1970", pos = {}, },
    { name = "Outstanding Variety, Music Or Comedy Series\t2011-2011", pos = {}, },
    { name = "Outstanding Variety, Music or Comedy Program\t1981-1991", pos = {}, },
    { name = "Outstanding Variety, Music or Comedy Program (Series)\t1992-1992", pos = {}, },
    { name = "Outstanding Variety, Music or Comedy Series\t1990-2010", pos = {}, },
    { name = "Outstanding Variety, Music or Comedy Special\t2007-2008", pos = {}, },
    { name = "Outstanding Video Tape Editing for a Limited Series or a Special\t1979-1984", pos = {}, },
    { name = "Outstanding Video Tape Editing for a Series\t1979-1984", pos = {}, },
    { name = "Outstanding Videotape Editing for a Series\t1985-1985", pos = {}, },
    { name = "Outstanding Voice-Over Performance\t1995-2013", pos = {}, },
    { name = "Outstanding Writing Achievement in Comedy\t1960-1973", pos = {}, },
    { name = "Outstanding Writing Achievement in Comedy or Variety\t1964-1964", pos = {}, },
    { name = "Outstanding Writing Achievement in Comedy, Variety or Music\t1969-1970", pos = {}, },
    { name = "Outstanding Writing Achievement in Drama\t1960-1973", pos = {}, },
    { name = "Outstanding Writing Achievement in Drama - Adaptation\t1964-1964", pos = {}, },
    { name = "Outstanding Writing Achievement in Drama - Original\t1964-1964", pos = {}, },
    { name = "Outstanding Writing Achievement in Drama - Original Teleplay\t1973-1973", pos = {}, },
    { name = "Outstanding Writing Achievement in Music or Variety\t1968-1968", pos = {}, },
    { name = "Outstanding Writing Achievement in Variety\t1966-1967", pos = {}, },
    { name = "Outstanding Writing Achievement in Variety or Music\t1971-1973", pos = {}, },
    { name = "Outstanding Writing for Non-Fiction Programming\t2003-2003", pos = {}, },
    { name = "Outstanding Writing for Nonfiction Programming\t2004-2017", pos = {}, },
    { name = "Outstanding Writing for a Comedy Series\t1996-2023", pos = {}, },
    { name = "Outstanding Writing for a Drama Series\t1995-2023", pos = {}, },
    { name = "Outstanding Writing for a Limited Series, Movie or Dramatic Special\t2020-2020", pos = {}, },
    { name = "Outstanding Writing for a Limited Series, Movie or a Dramatic Special\t2015-2019", pos = {}, },
    { name = "Outstanding Writing for a Limited or Anthology Series or Movie\t2021-2023", pos = {}, },
    { name = "Outstanding Writing for a Miniseries or a Movie\t1998-2001", pos = {}, },
    { name = "Outstanding Writing for a Miniseries or a Special\t1996-1996", pos = {}, },
    { name = "Outstanding Writing for a Miniseries, Movie or a Dramatic Special\t2002-2014", pos = {}, },
    { name = "Outstanding Writing for a Nonfiction Program\t2018-2023", pos = {}, },
    { name = "Outstanding Writing for a Variety Series\t2012-2023", pos = {}, },
    { name = "Outstanding Writing for a Variety Special\t2013-2018", pos = {}, },
    { name = "Outstanding Writing for a Variety or Music Program\t1996-1999", pos = {}, },
    { name = "Outstanding Writing for a Variety, Music or Comedy Program\t2000-2008", pos = {}, },
    { name = "Outstanding Writing for a Variety, Music or Comedy Series\t2009-2011", pos = {}, },
    { name = "Outstanding Writing in a Comedy Series\t1975-2013", pos = {}, },
    { name = "Outstanding Writing in a Comedy or Comedy-Variety or Music Series\t1979-1979", pos = {}, },
    { name = "Outstanding Writing in a Comedy-Variety or Music Series\t1975-1978", pos = {}, },
    { name = "Outstanding Writing in a Drama Series\t1975-1991", pos = {}, },
    { name = "Outstanding Writing in a Limited Series or a Special\t1979-1985", pos = {}, },
    { name = "Outstanding Writing in a Miniseries or a Special\t1986-1991", pos = {}, },
    { name = "Outstanding Writing in a Special Program - Drama or Comedy - Adaptation\t1975-1977", pos = {}, },
    { name = "Outstanding Writing in a Special Program - Drama or Comedy - Original Teleplay\t1976-1976", pos = {}, },
    { name = "Outstanding Writing in a Variety or Music Program\t1980-1993", pos = {}, },
    { name = "Outstanding Writing in a Variety, Music or Comedy Program\t1981-1981", pos = {}, },
    { name = "Program and Individual Achievements in Daytime Programming - Individuals\t1967-1967", pos = {}, },
    { name = "Program and Individual Achievements in Daytime Programming - Programs\t1967-1967", pos = {}, },
    { name = "Special Classification Achievements - Individuals (Variety Performances)\t1969-1969", pos = {}, },
    { name = "Special Classification Achievements - Programs\t1969-1969", pos = {}, },
    { name = "Special Classification of Individual Achievements\t1966-1968", pos = {}, },
    { name = "Special Classification of Outstanding Individual Achievement\t1977-1977", pos = {}, },
    { name = "Special Classification of Outstanding Individual Achievements - Special Photographic Effects\t1969-1969", pos = {}, },
    { name = "Special Classification of Outstanding Program Achievement\t1977-1978", pos = {}, },
    { name = "Special Classification of Outstanding Program and Individual Achievement\t1974-1976", pos = {}, },
    { name = "Special Classification of Outstanding Program and Individual Achievement - General Programming\t1972-1972", pos = {}, },
    { name = "Special Classification of Outstanding Program and Individual Achievement - Individuals\t1970-1971", pos = {}, },
    { name = "Special Classification of Outstanding Program and Individual Achievement - Programs\t1971-1971", pos = {}, },
    { name = "Special Classification of Outstanding Program and Individual Achievements - Programs\t1970-1970", pos = {}, },
    { name = "Special Classifications of Individual Achievements\t1967-1967", pos = {}, },
    { name = "The Program of the Year\t1961-1964", pos = {}, },
    { name = "Writer of the Year - Series\t1974-1974", pos = {}, },
}

function writeItem(f, item)
    f:write("{ name = ")
    f:write(string.format("%q", item.name))
    f:write(", pos = {")
    for _, value in ipairs(item.pos) do
        f:write("{ v = ")
        f:write(value.v)
        f:write(", x = ")
        f:write(value.x)
        f:write(", y = ")
        f:write(value.y)
        f:write(" }, ")
    end
    f:write("}")
end
